// Generate a Rust test that checks the two evaluators agree.
//
// There are two implementations of the same instruction set: `src/evaluate.ts` (the reference,
// used by the front-end tests) and `runtime/src/eval.rs` (the one that ships). Two
// implementations of anything drift. This script closes the loop.
//
// It compiles each example with the front end, samples its state range, records what the
// TypeScript evaluator returns, and writes those samples into a Rust test as literals. `cargo
// test` then fails if the Rust runtime disagrees.
//
// Run: node scripts/differential.mjs   (then: cargo test --manifest-path runtime/Cargo.toml)

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { compileSource, evaluate } from '../out/src/index.js';

const EXAMPLES = 'examples';
const OUT = 'runtime/tests/differential.rs';
const SAMPLES = 400;

/** The state range to sweep per example. Chosen to cross every breakpoint the example has. */
const RANGES = {
    'ramp.ride': [0, 800],
    'projectile.ride': [0, 6],
};

function rustOp(op) {
    switch (op.op) {
        case 'Push':
            return `Op::Push(f32::from_bits(${bits(op.value)}))`;
        case 'LoadState':
            return `Op::LoadState(${op.index})`;
        case 'LoadLocal':
            return `Op::LoadLocal(${op.index})`;
        case 'StoreLocal':
            return `Op::StoreLocal(${op.index})`;
        case 'Jump':
            return `Op::Jump(${op.target})`;
        case 'JumpIfFalse':
            return `Op::JumpIfFalse(${op.target})`;
        case 'Call':
            return `Op::Call { target: ${op.target}, arity: ${op.arity}, fp_delta: ${op.fpDelta} }`;
        default:
            return `Op::${op.op}`;
    }
}

/** The exact f32 bit pattern, so no decimal round-trip can lose a bit. */
function bits(value) {
    const buf = new DataView(new ArrayBuffer(4));
    buf.setFloat32(0, Math.fround(value));
    return '0x' + buf.getUint32(0).toString(16).padStart(8, '0');
}

function rustFunc(f) {
    return `Func { entry: ${f.entry}, len: ${f.len}, arity: ${f.arity}, frame: ${f.frame} }`;
}

const header = `// GENERATED by scripts/differential.mjs — do not edit by hand.
//
// Each case below holds a program compiled by the TypeScript front end, plus the values the
// TypeScript reference evaluator produced for it. This test fails if the Rust runtime
// disagrees, which is what keeps the two implementations of one instruction set together.
//
// WHY A TOLERANCE AND NOT EXACT EQUALITY: the arithmetic, comparison, branch and call
// instructions are bit-exact across both evaluators. The transcendentals are not guaranteed to
// be. \`Math.cos\` computes in f64 and is rounded to f32; Rust's \`f32::cos\` computes in f32
// throughout, so the two can differ in the last bit. The tolerance is wide enough to absorb
// that and far too narrow to absorb a real fault: a wrong branch, a wrong frame slot or a
// mispatched jump moves the result by orders of magnitude, not by an ulp.

use ride_runtime::{Func, Op, Program, Verified};

/// Relative tolerance. See the note above.
const TOL: f32 = 1e-5;

fn check(name: &str, program: Program, cases: &[(f32, f32)]) {
    let v = Verified::new(program)
        .unwrap_or_else(|e| panic!("{name}: the front end emitted bytecode the verifier rejected: {}", e.code()));
    for &(input, want) in cases {
        let got = v.eval(&[input]).expect("one state field");
        let scale = want.abs().max(1.0);
        assert!(
            (got - want).abs() <= TOL * scale,
            "{name}: at state {input} the runtime gave {got}, the reference gave {want}"
        );
    }
}
`;

const files = (await readdir(EXAMPLES)).filter((f) => f.endsWith('.ride')).sort();
const blocks = [];

for (const file of files) {
    const source = await readFile(join(EXAMPLES, file), 'utf8');
    const result = await compileSource(source, `file:///${file}`);
    if (!result.ok) {
        console.error(`${file} did not compile:`);
        for (const e of result.errors) console.error('  ' + e.message);
        process.exit(1);
    }
    const b = result.bytecode;
    if (b.stateArity !== 1) {
        console.error(`${file}: this harness sweeps one state field, found ${b.stateArity}`);
        process.exit(1);
    }

    const [lo, hi] = RANGES[file] ?? [0, 1];
    const cases = [];
    for (let i = 0; i <= SAMPLES; i++) {
        const s = Math.fround(lo + ((hi - lo) * i) / SAMPLES);
        cases.push([s, evaluate(b, [s])]);
    }

    const ident = file.replace(/\.ride$/, '').replace(/[^a-z0-9]+/gi, '_');
    blocks.push(`
#[test]
fn differential_${ident}() {
    // ${file} — ${b.funcs.length} function(s), ${b.code.length} instruction(s), swept over [${lo}, ${hi}]
    let program = Program {
        code: vec![
            ${b.code.map(rustOp).join(',\n            ')},
        ],
        funcs: vec![
            ${b.funcs.map(rustFunc).join(',\n            ')},
        ],
        state_arity: ${b.stateArity},
    };
    let cases: &[(f32, f32)] = &[
        ${cases.map(([s, y]) => `(f32::from_bits(${bits(s)}), f32::from_bits(${bits(y)}))`).join(',\n        ')},
    ];
    check("${file}", program, cases);
}`);
    console.log(`${file}: ${b.code.length} instructions, ${cases.length} samples`);
}

await writeFile(OUT, header + blocks.join('\n') + '\n');
console.log(`wrote ${OUT}`);
